# Generated by Django 4.2.3 on 2023-07-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUpload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
